version: '3.3'

volumes:
  data:

services:

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
       - app-networks

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    env_file:
      - ".env"
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - TZ=GMT
    networks:
      - app-networks

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-networks

  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always
    networks:
      - app-networks

  app:
    build: .
    container_name: ${NAME_APP_WEB}
    ports:
      - "8000:80"
      - "4000:443"
    restart: always
    depends_on:
      - db
      - redis
      - mail
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/usr/share/nginx"
      - "./setup.sh:/usr/local/bin/setup.sh"
      - "./etc/ssl:/etc/ssl"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge